### ISSUE TITLE
"Select 2 Fields" even when I have

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/data-analysis#5]
<img width="763" alt="Screen Shot 2022-01-06 at 11 59 01" src="https://user-images.githubusercontent.com/7927356/148420640-993f6fee-4ff8-479e-bb2b-c3d9ca7de123.png">

**Comment by SkepticMystic** [comment]
That's strange, it works for my test data:
![image](https://user-images.githubusercontent.com/70717676/148429956-6e648ef7-2497-43ec-9a64-08c4e50f12c2.png)

I think the issue is that there is a value in one of those fields that isn't actually numeric. I saw an example of this where `field:: .85` was treated as a string, not a number. Those will need to be changed to `field:: 0.85`

**Comment by arminta7** [comment]
Yes, I think you might be right. I have some weird entries that I'll go back and fix.

**Comment by arminta7** [comment]
That fixed it! Thanks!
